#!/usr/bin/env python3
"""
Claude AI Agent — GitHub Issue Responder
Part of: AI HOLDINGS OS 2026 | Iizuka City, Fukuoka
Repository: ShinnosukeMoriFukuokaJP/Iizuka-LinkedIn-Network-Repository-Structure

Trigger: Issue labeled with 'ai-agent'
Action : Claude reads issue → posts structured PSI response as comment
"""

import os
import json
import urllib.request
import urllib.error
import anthropic

# ── Config ────────────────────────────────────────────────────────
ANTHROPIC_API_KEY = os.environ["ANTHROPIC_API_KEY"]
GITHUB_TOKEN      = os.environ["GITHUB_TOKEN"]
REPO              = os.environ["REPO"]
ISSUE_NUMBER      = os.environ["ISSUE_NUMBER"]
ISSUE_TITLE       = os.environ.get("ISSUE_TITLE", "")
ISSUE_BODY        = os.environ.get("ISSUE_BODY", "")
ISSUE_AUTHOR      = os.environ.get("ISSUE_AUTHOR", "")

SYSTEM_PROMPT = """You are an AI assistant embedded in the Iizuka LinkedIn Network GitHub repository.
This repository serves the Fukuoka/Kyushu SME ecosystem and the AI HOLDINGS OS 2026 framework.

When responding to GitHub issues:
1. Analyze the issue using Problem → Solution → Impact (PSI) structure
2. Be concise, actionable, and honest — no fabricated information
3. If the issue is a feature request, outline a realistic implementation path
4. If the issue is a bug, identify the likely cause and suggest a fix
5. If the issue is a question, answer directly with relevant context
6. Always end with a clear next step for the issue author

Language: Match the language of the issue (Japanese or English).
Tone: Professional but approachable. Regional context (Fukuoka/Kyushu) is relevant.
"""

def build_prompt() -> str:
    return f"""GitHub Issue #{ISSUE_NUMBER} in {REPO}

Author: {ISSUE_AUTHOR}
Title: {ISSUE_TITLE}

Body:
{ISSUE_BODY or "(no body provided)"}

Please analyze this issue and provide a structured response."""


def call_claude(prompt: str) -> str:
    client = anthropic.Anthropic(api_key=ANTHROPIC_API_KEY)
    message = client.messages.create(
        model="claude-sonnet-4-6",
        max_tokens=1024,
        system=SYSTEM_PROMPT,
        messages=[{"role": "user", "content": prompt}]
    )
    return message.content[0].text


def post_github_comment(body: str) -> None:
    url = f"https://api.github.com/repos/{REPO}/issues/{ISSUE_NUMBER}/comments"
    payload = json.dumps({"body": body}).encode("utf-8")
    req = urllib.request.Request(
        url,
        data=payload,
        method="POST",
        headers={
            "Authorization": f"token {GITHUB_TOKEN}",
            "Content-Type": "application/json",
            "Accept": "application/vnd.github.v3+json",
            "User-Agent": "ClaudeAgent/1.0"
        }
    )
    with urllib.request.urlopen(req) as r:
        result = json.loads(r.read())
        print(f"Comment posted: {result.get('html_url')}")


def format_response(claude_response: str) -> str:
    return f"""<!-- Claude AI Agent Response -->
> 🤖 **Claude AI Agent** — *AI HOLDINGS OS 2026*

{claude_response}

---
*Generated by [Claude AI Agent](https://github.com/{REPO}/blob/main/.github/workflows/ai-agent.yml) · [Career Signal System](https://github.com/{REPO}/tree/main/career-signal-system)*
"""


if __name__ == "__main__":
    print(f"Processing Issue #{ISSUE_NUMBER}: {ISSUE_TITLE}")

    prompt   = build_prompt()
    response = call_claude(prompt)
    comment  = format_response(response)

    post_github_comment(comment)
    print("Done.")
