#!/usr/bin/env python3
"""
Claude AI Agent v3 — JSON context経由でIssue情報を受け取る
特殊文字・改行を含むIssue bodyに対応
AI HOLDINGS OS 2026 | Iizuka City, Fukuoka
"""

import os
import json
import urllib.request
import urllib.error

# ── Issue context をJSONファイルから読み込む ──────────────────────
CONTEXT_PATH = os.environ.get("ISSUE_CONTEXT_PATH", "/tmp/issue_context.json")
with open(CONTEXT_PATH) as f:
    ctx = json.load(f)

ANTHROPIC_API_KEY = os.environ["ANTHROPIC_API_KEY"]
GITHUB_TOKEN      = os.environ["GITHUB_TOKEN"]
REPO              = ctx["repo"]
ISSUE_NUMBER      = ctx["issue_number"]
ISSUE_TITLE       = ctx["issue_title"]
ISSUE_BODY        = ctx["issue_body"]
ISSUE_AUTHOR      = ctx["issue_author"]

SYSTEM_PROMPT = """You are an AI assistant embedded in the Iizuka LinkedIn Network GitHub repository.
This repository serves the Fukuoka/Kyushu SME ecosystem and the AI HOLDINGS OS 2026 framework.

When responding to GitHub issues:
1. Analyze the issue using Problem → Solution → Impact (PSI) structure
2. Be concise, actionable, and honest — no fabricated information
3. If the issue is a feature request, outline a realistic implementation path
4. If the issue is a bug, identify the likely cause and suggest a fix
5. If the issue is a question, answer directly with relevant context
6. Always end with a clear next step for the issue author

Language: Match the language of the issue (Japanese or English).
Tone: Professional but approachable. Regional context (Fukuoka/Kyushu) is relevant.
"""


def call_claude() -> str:
    prompt = f"""GitHub Issue #{ISSUE_NUMBER} in {REPO}

Author: {ISSUE_AUTHOR}
Title: {ISSUE_TITLE}

Body:
{ISSUE_BODY or "(no body provided)"}

Please analyze this issue and provide a structured response."""

    payload = json.dumps({
        "model": "claude-sonnet-4-6",
        "max_tokens": 1024,
        "system": SYSTEM_PROMPT,
        "messages": [{"role": "user", "content": prompt}]
    }).encode("utf-8")

    req = urllib.request.Request(
        "https://api.anthropic.com/v1/messages",
        data=payload,
        method="POST",
        headers={
            "x-api-key": ANTHROPIC_API_KEY,
            "anthropic-version": "2023-06-01",
            "content-type": "application/json",
        }
    )
    with urllib.request.urlopen(req) as r:
        data = json.loads(r.read())
        return data["content"][0]["text"]


def post_github_comment(body: str) -> None:
    url = f"https://api.github.com/repos/{REPO}/issues/{ISSUE_NUMBER}/comments"
    payload = json.dumps({"body": body}).encode("utf-8")
    req = urllib.request.Request(
        url, data=payload, method="POST",
        headers={
            "Authorization": f"token {GITHUB_TOKEN}",
            "Content-Type": "application/json",
            "Accept": "application/vnd.github.v3+json",
            "User-Agent": "ClaudeAgent/3.0"
        }
    )
    with urllib.request.urlopen(req) as r:
        result = json.loads(r.read())
        print(f"✅ Comment posted: {result.get('html_url')}")


def format_response(claude_response: str) -> str:
    return f"""<!-- Claude AI Agent v3 -->
> 🤖 **Claude AI Agent** (claude-sonnet-4-6) — *AI HOLDINGS OS 2026*

{claude_response}

---
*Generated by [Claude AI Agent](https://github.com/{REPO}/blob/main/.github/workflows/ai-agent.yml) · [Career Signal System](https://github.com/{REPO}/tree/main/career-signal-system)*
"""


if __name__ == "__main__":
    print(f"Processing Issue #{ISSUE_NUMBER}: {ISSUE_TITLE}")
    response = call_claude()
    comment  = format_response(response)
    post_github_comment(comment)
    print("Done.")
