"""
generate_posts.py
旅行記録Markdownを読み込み、LinkedIn投稿文（英語・日本語）を生成する。
APIコストゼロのテンプレートベース生成。
"""
import re
import os
from datetime import date

INPUT_FILE = "input/travel-record.md"
OUTPUT_EN = "output/post-en.md"
OUTPUT_JA = "output/post-ja.md"

HASHTAGS_EN = (
    "#OpenSource #GitHub #Japan #TravelTech #AITools "
    "#IndoPacific #JLI_OS #AIHoldingsOS2026 #Fukuoka #OSS"
)
HASHTAGS_JA = (
    "#OpenSource #GitHub #旅行 #AI活用 #DX "
    "#九州 #福岡 #JLI_OS #AIHoldingsOS2026 #OSS"
)


def parse_frontmatter(text: str) -> dict:
    """---で囲まれたYAMLフロントマターをパース（簡易版）"""
    meta = {}
    match = re.search(r"^---\n(.*?)\n---", text, re.DOTALL)
    if not match:
        return meta
    for line in match.group(1).splitlines():
        if ":" in line:
            key, _, value = line.partition(":")
            meta[key.strip()] = value.strip()
    return meta


def extract_section(text: str, heading: str) -> str:
    """## 見出し以下のテキストを抽出"""
    pattern = rf"## {re.escape(heading)}\n(.*?)(?=\n## |\Z)"
    match = re.search(pattern, text, re.DOTALL)
    return match.group(1).strip() if match else ""


def bullets_to_list(text: str) -> list:
    """箇条書きテキストをリストに変換"""
    return [
        line.lstrip("-・• ").strip()
        for line in text.splitlines()
        if line.strip().startswith(("-", "・", "•"))
    ]


def generate_post_en(meta: dict, built: list, city_desc: str) -> str:
    city = meta.get("city", "[CITY]")
    prefecture = meta.get("prefecture", "[PREFECTURE]")
    period = meta.get("period", "[PERIOD]")
    repo_url = meta.get("repo_url", "[REPO URL]")
    tools = meta.get("tools", "iPhone, AI tools (free tier), GitHub")

    built_lines = "\n".join(f"• {item}" for item in built) if built else "• Travel record in Markdown"

    return f"""Just turned my trip to {city} into an open-source project on GitHub.

{period} in {city}, {prefecture}, Japan — here's what I built:

📁 {repo_url}

What's inside:
{built_lines}

Built with:
• {tools}
• 100% free-tier tools — iPhone only, no PC

{city_desc}

This is part of JLI-OS — open knowledge infrastructure for every city in Japan,
starting from Iizuka, Fukuoka.

Fork the repo and adapt it for your city 👇
{repo_url}

{HASHTAGS_EN}

---
*Generated by linkedin-travel-post-generator | AI HOLDINGS OS 2026*
*⚠️ Review before posting: check for personal info, verify facts, adjust tone as needed.*
"""


def generate_post_ja(meta: dict, built: list, city_desc: str) -> str:
    city = meta.get("city", "[都市名]")
    period = meta.get("period", "[期間]")
    repo_url = meta.get("repo_url", "[リポジトリURL]")
    tools = meta.get("tools", "iPhone・AIツール（無料プラン）・GitHub")

    built_lines = "\n".join(f"・{item}" for item in built) if built else "・旅行記録Markdown"

    return f"""{city}への旅行を、GitHubのOSSプロジェクトに変えました。

{period}で作ったもの：

📁 {repo_url}

収録内容：
{built_lines}

使ったツール：
・{tools}
・すべて無料プランの範囲内（2026年6月時点）・PCなし

{city_desc}

これはJLI-OSプロジェクトの一部です。
飯塚市をスタートとして、日本中の都市の知識インフラをGitHubで構築しています。

ぜひForkして、あなたの都市版を作ってみてください。
{repo_url}

{HASHTAGS_JA}

---
*linkedin-travel-post-generator により生成 | AI HOLDINGS OS 2026*
*⚠️ 投稿前に確認：個人情報が含まれていないか・事実を確認・表現を調整してください。*
"""


def main():
    if not os.path.exists(INPUT_FILE):
        print(f"ERROR: {INPUT_FILE} が見つかりません。")
        return

    with open(INPUT_FILE, encoding="utf-8") as f:
        content = f.read()

    meta = parse_frontmatter(content)
    built_text = extract_section(content, "作ったもの")
    built = bullets_to_list(built_text)
    city_desc = extract_section(content, "都市の特徴")

    os.makedirs("output", exist_ok=True)

    post_en = generate_post_en(meta, built, city_desc)
    post_ja = generate_post_ja(meta, built, city_desc)

    with open(OUTPUT_EN, "w", encoding="utf-8") as f:
        f.write(post_en)
    with open(OUTPUT_JA, "w", encoding="utf-8") as f:
        f.write(post_ja)

    print(f"✅ 英語投稿生成: {OUTPUT_EN}")
    print(f"✅ 日本語投稿生成: {OUTPUT_JA}")
    print(f"生成日: {date.today()}")
    print("")
    print("⚠️  投稿前に必ず確認してください:")
    print("  - 他者の個人情報が含まれていないか（個人情報保護法）")
    print("  - 事実と異なる内容がないか")
    print("  - 断定的な無料表現は修正する（景品表示法）")


if __name__ == "__main__":
    main()
