import json
import os
import pathlib
import urllib.request
import urllib.error
from datetime import datetime, timezone

HF_TOKEN  = os.environ.get("HF_TOKEN", "")
MODEL     = "mistralai/Mistral-7B-Instruct-v0.3"
API_BASE  = "https://api-inference.huggingface.co/models"
SEC_START = "<!-- AI_SUMMARY_START -->"
SEC_END   = "<!-- AI_SUMMARY_END -->"


def call_hf(prompt):
    if not HF_TOKEN:
        return "[HF_TOKEN未設定]"
    url     = f"{API_BASE}/{MODEL}"
    payload = json.dumps({
        "inputs": f"<s>[INST] {prompt} [/INST]",
        "parameters": {"max_new_tokens": 256, "return_full_text": False},
    }).encode()
    req = urllib.request.Request(
        url, data=payload,
        headers={"Authorization": f"Bearer {HF_TOKEN}", "Content-Type": "application/json"},
        method="POST",
    )
    try:
        with urllib.request.urlopen(req, timeout=60) as resp:
            data = json.loads(resp.read())
            return data[0].get("generated_text", "") if isinstance(data, list) else str(data)
    except Exception as e:
        return f"[Error: {e}]"


def update_readme(summary):
    readme = pathlib.Path("README.md")
    if not readme.exists():
        readme.write_text(f"# Iizuka LinkedIn Network\n\n{SEC_START}\n{SEC_END}\n")
    content = readme.read_text(encoding="utf-8")
    now     = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    section = (
        f"{SEC_START}\n## 🤖 AI-Generated Summary\n\n"
        f"> Last updated: {now}\n\n{summary}\n\n"
        f"*Generated by Claude × HuggingFace Pipeline*\n{SEC_END}"
    )
    if SEC_START in content and SEC_END in content:
        before  = content[:content.index(SEC_START)]
        after   = content[content.index(SEC_END) + len(SEC_END):]
        updated = before + section + after
    else:
        updated = content + "\n\n" + section
    readme.write_text(updated, encoding="utf-8")
    print("✅ README.md updated")


def main():
    prompt = (
        "Summarize in 3 bullet points: Iizuka LinkedIn Network Repository — "
        "regional networking, AI automation pipeline, DevSecOps security layer."
    )
    print("🤖 Generating summary...")
    summary = call_hf(prompt)
    update_readme(summary)


if __name__ == "__main__":
    main()
