name: AI Runner

on:
  workflow_dispatch:   # 手動実行できる

jobs:
  run-ai:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v7

      - name: setup python
        uses: actions/setup-python@v6
        with:
          python-version: "3.11"

      - name: install dependencies
        run: pip install openai

      - name: run script
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: python main.py

      - name: upload result
        uses: actions/upload-artifact@v7
        with:
          name: output
          path: output.txt
